### ISSUE TITLE
Error: undefined method `view_cache_dependencies' in Rails 4.2.7

### ISSUE THREAD

**Issue by gmcnaughton** [gilest/mailer_fragment_caching#3]
Using mailer_fragment_caching 0.0.4 + Rails 4.2.7, I get the following error when trying to send mail with a cached fragment:

     Failure/Error: MyMailer.send_something(...).deliver_now
     ActionView::Template::Error:
       undefined local variable or method `view_cache_dependencies' for #<#<Class:0x007fa149a70548>:0x007fa14ade13e8>

The problem seems to be that `ActionView::Helpers::CacheHelper#fragment_name_with_digest` calls `view_cache_dependencies`, which isn't defined.

For controllers, that method comes from ActionPack's `ActionController::Caching`, but mailers don't have it.

Any advice on how to get this working in Rails4? :)

**Comment by gilest** [comment]
Hey – thanks for contributing this 😄 

Since Rails 5 includes this feature I'm not really supporting the gem any longer.

It's probably as simple as including the missing method in the `MailerFragmentCaching` module. You're welcome to have a go with it – send me a PR if it works.

**Comment by gmcnaughton** [comment]
Great!  I sent a PR, though I only tested it in 4.2.7.  In the next couple days I'll try to test 4.0 and 4.1 as well.

Unfortunately it required copy-pasting a bit of logic from `ActionController::Caching`.

Thanks for the gem! 💜
