### ISSUE TITLE
Can you please add a license?

### ISSUE THREAD

**Issue by aouji** [gilest/mailer_fragment_caching#5]
Hi, I have tested your gem in my Rails 4.2 app and it works like a charm! Thank you for that! To go to production with it I need to know your gem's license to see if I can use it. Will it be possible for you to add a license? Thanks!

**Comment by gilest** [comment]
Hi there I've added the MIT license for you.

Would you like me to release an updated version of the gem with the license included also?

**Comment by aouji** [comment]
It will be great if you do. Thanks so much for the fast response!

**Comment by gilest** [comment]
Version `0.0.6` is now on rubygems with the MIT license included.

**Comment by aouji** [comment]
Thank you sir!
